import type { Request, Response } from "express";
import { Router } from "express";
import { serverSupabase } from "../lib/supabase";
import { runPythonScript } from "../lib/python";

const router = Router();

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

router.post(
  "/api/schools/:schoolId/timetables/generate",
  async (req: Request, res: Response) => {
    const { schoolId } = req.params;

    if (!UUID_REGEX.test(schoolId)) {
      return res.status(400).json({ error: "Invalid schoolId" });
    }

    try {
      // Fetch core data needed for generation
      const [teachersRes, subjectsRes, streamsRes] = await Promise.all([
        serverSupabase
          .from("teachers")
          .select("id, max_periods_per_day, max_periods_per_week")
          .eq("school_id", schoolId)
          .eq("is_active", true),
        serverSupabase
          .from("subjects")
          .select("id, name, duration_minutes")
          .eq("school_id", schoolId)
          .eq("is_active", true),
        serverSupabase
          .from("streams")
          .select("id, grade_level, name")
          .eq("school_id", schoolId)
          .eq("is_active", true),
      ]);

      if (teachersRes.error) throw teachersRes.error;
      if (subjectsRes.error) throw subjectsRes.error;
      if (streamsRes.error) throw streamsRes.error;

      const teachers = teachersRes.data || [];
      const subjects = subjectsRes.data || [];
      const streams = streamsRes.data || [];

      if (!teachers.length || !subjects.length || !streams.length) {
        return res.status(400).json({
          error:
            "Missing required data. Ensure teachers, subjects, and streams are configured.",
        });
      }

      // Get teacher-subject capabilities
      const teacherSubjectsRes = await serverSupabase
        .from("teacher_subjects")
        .select("teacher_id, subject_id");
      if (teacherSubjectsRes.error) throw teacherSubjectsRes.error;

      // Find active timetable config for the school
      const configRes = await serverSupabase
        .from("timetable_configs")
        .select("id, school_id")
        .eq("school_id", schoolId)
        .eq("is_active", true)
        .limit(1)
        .maybeSingle();

      if (configRes.error) throw configRes.error;
      const config = configRes.data;

      if (!config) {
        return res.status(400).json({
          error:
            "No active timetable configuration found. Please configure timetable settings first.",
        });
      }

      const periodsRes = await serverSupabase
        .from("periods")
        .select("id, day_of_week, period_number, start_time, end_time, is_break")
        .eq("timetable_config_id", config.id)
        .eq("is_break", false);

      if (periodsRes.error) throw periodsRes.error;

      const periods = periodsRes.data || [];

      if (!periods.length) {
        return res.status(400).json({
          error:
            "No teaching periods configured. Please add periods to the active timetable configuration.",
        });
      }

      const pythonInput = {
        school_id: schoolId,
        teachers,
        subjects,
        teacher_subjects: teacherSubjectsRes.data || [],
        streams,
        periods,
      };

      const pythonResult = await runPythonScript<{
        entries: Array<{
          period_id: string;
          stream_id: string;
          subject_id: string;
          teacher_id: string;
          day_of_week: number;
        }>;
      }>("scripts/generate_timetable.py", pythonInput);

      if (!pythonResult.ok || !pythonResult.data) {
        return res.status(500).json({
          error:
            pythonResult.error ||
            "Python generator failed without a specific error message.",
        });
      }

      const { entries } = pythonResult.data;

      if (!entries || !entries.length) {
        return res
          .status(400)
          .json({ error: "No timetable entries generated by Python script." });
      }

      // Clear previous generated entries for this config
      const deleteRes = await serverSupabase
        .from("timetable_entries")
        .delete()
        .eq("timetable_config_id", config.id);

      if (deleteRes.error) throw deleteRes.error;

      const insertPayload = entries.map((e) => ({
        timetable_config_id: config.id,
        period_id: e.period_id,
        stream_id: e.stream_id,
        subject_id: e.subject_id,
        teacher_id: e.teacher_id,
        day_of_week: e.day_of_week,
      }));

      const insertRes = await serverSupabase
        .from("timetable_entries")
        .insert(insertPayload);

      if (insertRes.error) throw insertRes.error;

      // Store a summary record for history / templates linkage
      const summaryRes = await serverSupabase.from("timetables").insert([
        {
          school_id: schoolId,
          input_snapshot: pythonInput,
          generated_timetable: { entries },
          status: "generated",
        },
      ]);

      if (summaryRes.error) {
        // Log but don't fail the whole request if history insert fails
        // eslint-disable-next-line no-console
        console.warn("[timetables.generate] failed to insert summary:", summaryRes.error);
      }

      return res.status(200).json({
        success: true,
        timetable_config_id: config.id,
        entries_created: entries.length,
      });
    } catch (error: any) {
      // eslint-disable-next-line no-console
      console.error("[timelines.generate] error:", error);
      return res
        .status(500)
        .json({ error: error.message || "Failed to generate timetable" });
    }
  }
);

export default router;


