// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const SUPABASE_FUNCTIONS_URL = import.meta.env.VITE_SUPABASE_FUNCTIONS_URL;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    '⚠️ Supabase environment variables are missing!\n' +
    'Please create a .env file with:\n' +
    'VITE_SUPABASE_URL=your_supabase_url\n' +
    'VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_anon_key'
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
    ...(SUPABASE_FUNCTIONS_URL
      ? {
          functions: {
            url: SUPABASE_FUNCTIONS_URL,
          },
        }
      : {}),
  }
);

// Set up automatic token refresh before it expires
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
    if (session?.expires_at) {
      const expiresIn = session.expires_at - Math.floor(Date.now() / 1000);
      // Refresh token 5 minutes before expiration
      const refreshTime = (expiresIn - 300) * 1000;
      if (refreshTime > 0) {
        setTimeout(() => {
          supabase.auth.refreshSession();
        }, refreshTime);
      }
    }
  }
});